/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}', './index.html'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-primary)',
        'bg-sidebar': 'var(--bg-sidebar)',
        'bg-statusbar': 'var(--bg-statusbar)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-hover': 'var(--bg-hover)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-faint': 'var(--text-faint)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-tab': 'var(--border-tab)',
        // Historical name kept for ABI; value is amber.
        'accent-blue': 'var(--accent-blue)',
        'accent-amber': 'var(--accent-amber)',
        'accent-amber-dim': 'var(--accent-amber-dim)',
        'status-running': 'var(--status-running)',
        'status-idle': 'var(--status-idle)',
        'status-warning': 'var(--status-warning)',
        'status-error': 'var(--status-error)',
        'status-stopped': 'var(--status-stopped)',
        'status-live': 'var(--status-live)',
        'status-err': 'var(--status-err)',
      },
      fontFamily: {
        sans: [
          '"JetBrains Mono"',
          '"Berkeley Mono"',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Consolas',
          'monospace',
        ],
        mono: [
          '"JetBrains Mono"',
          '"Berkeley Mono"',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Consolas',
          'monospace',
        ],
      },
    },
  },
  plugins: [],
};
